[package]
name = "lucidity-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lucidity-pairing = { path = "../lucidity-pairing" }

[dev-dependencies]
k9 = "0.11.0"
serde_json = "1.0"
